
from manim import *

class Solution(Scene):
    def construct(self):
        # Step description
        step_desc = MathTex(r"\text{Change of variables: Let } v = \frac{1}{y}, \text{ then } y = \frac{1}{v}").to_edge(UP).scale(0.75)
        
        # Equations
        eq1 = MathTex(r"\frac{dy}{dx} = -\frac{1}{v^2} \frac{dv}{dx}").move_to(ORIGIN).scale(0.75)
        eq2 = MathTex(r"-\frac{1}{v^2} \frac{dv}{dx} + \frac{1}{v} = \frac{1}{v^2}(\cos x - \sin x)").move_to(ORIGIN).scale(0.75)
        eq3 = MathTex(r"-\frac{dv}{dx} + v = \cos x - \sin x").move_to(ORIGIN).scale(0.75)
        eq4 = MathTex(r"\frac{dv}{dx} - v = \sin x - \cos x").move_to(ORIGIN).scale(0.75)
        eq5 = MathTex(r"\mu(x) = e^{\int -1 \, dx} = e^{-x}").move_to(ORIGIN).scale(0.75)
        eq6 = MathTex(r"e^{-x} \frac{dv}{dx} - e^{-x} v = e^{-x} (\sin x - \cos x)").move_to(ORIGIN).scale(0.75)
        eq7 = MathTex(r"\frac{d}{dx}(v e^{-x}) = e^{-x} (\sin x - \cos x)").move_to(ORIGIN).scale(0.75)
        eq8 = MathTex(r"v e^{-x} = \int e^{-x} (\sin x - \cos x) \, dx").move_to(ORIGIN).scale(0.75)
        eq9 = MathTex(r"\int e^{-x} (\sin x - \cos x) \, dx = -e^{-x}(\sin x - \cos x) - \int -e^{-x}(\cos x + \sin x) \, dx").move_to(ORIGIN).scale(0.75)
        eq10 = MathTex(r"= -e^{-x}(\sin x - \cos x) + \int e^{-x}(\cos x + \sin x) \, dx").move_to(ORIGIN).scale(0.75)
        eq11 = MathTex(r"= -e^{-x}(\sin x - \cos x) + \left[-e^{-x}(\cos x + \sin x) - \int -e^{-x}(\sin x - \cos x) \, dx\right]").move_to(ORIGIN).scale(0.75)
        eq12 = MathTex(r"I = -e^{-x}(\sin x - \cos x) - e^{-x}(\cos x + \sin x) - I").move_to(ORIGIN).scale(0.75)
        eq13 = MathTex(r"2I = -e^{-x}(\sin x - \cos x) - e^{-x}(\cos x + \sin x)").move_to(ORIGIN).scale(0.75)
        eq14 = MathTex(r"I = -\frac{1}{2}e^{-x}(2\sin x)").move_to(ORIGIN).scale(0.75)
        eq15 = MathTex(r"I = -e^{-x}\sin x").move_to(ORIGIN).scale(0.75)
        eq16 = MathTex(r"v e^{-x} = -e^{-x}\sin x + C").move_to(ORIGIN).scale(0.75)
        eq17 = MathTex(r"v = -\sin x + Ce^{x}").move_to(ORIGIN).scale(0.75)
        eq18 = MathTex(r"y = \frac{1}{-\sin x + Ce^{x}}").move_to(ORIGIN).scale(0.75)

        # Animation sequence
        self.play(Write(step_desc))
        self.play(Write(eq1))
        self.wait(2)
        self.play(ReplacementTransform(eq1, eq2))
        self.wait(2)
        self.play(ReplacementTransform(eq2, eq3))
        self.wait(2)
        self.play(ReplacementTransform(eq3, eq4))
        self.wait(2)
        self.play(ReplacementTransform(eq4, eq5))
        self.wait(2)
        self.play(ReplacementTransform(eq5, eq6))
        self.wait(2)
        self.play(ReplacementTransform(eq6, eq7))
        self.wait(2)
        self.play(ReplacementTransform(eq7, eq8))
        self.wait(2)
        self.play(ReplacementTransform(eq8, eq9))
        self.wait(2)
        self.play(ReplacementTransform(eq9, eq10))
        self.wait(2)
        self.play(ReplacementTransform(eq10, eq11))
        self.wait(2)
        self.play(ReplacementTransform(eq11, eq12))
        self.wait(2)
        self.play(ReplacementTransform(eq12, eq13))
        self.wait(2)
        self.play(ReplacementTransform(eq13, eq14))
        self.wait(2)
        self.play(ReplacementTransform(eq14, eq15))
        self.wait(2)
        self.play(ReplacementTransform(eq15, eq16))
        self.wait(2)
        self.play(ReplacementTransform(eq16, eq17))
        self.wait(2)
        self.play(ReplacementTransform(eq17, eq18))
        self.wait(2)
        self.play(FadeOut(step_desc), FadeOut(eq18))
