
from manim import *

class Solution(Scene):
    def construct(self):
        # Section 1: Show that ((x + y)dx + x , dy) is an exact differential
        description1 = MathTex(r"\text{Show that } (x + y)dx + x \, dy \text{ is an exact differential}").to_edge(UP)
        eq1_1 = MathTex(r"dF = \frac{\partial F}{\partial x} \, dx + \frac{\partial F}{\partial y} \, dy = (x + y) \, dx + x \, dy").move_to(ORIGIN)
        eq1_2 = MathTex(r"\frac{\partial F}{\partial x} = x + y \quad \text{and} \quad \frac{\partial F}{\partial y} = x").move_to(ORIGIN)
        eq1_3 = MathTex(r"F(x, y) = \int (x + y) \, dx = \frac{x^2}{2} + xy + g(y)").move_to(ORIGIN)
        eq1_4 = MathTex(r"\frac{\partial F}{\partial y} = x + g'(y)").move_to(ORIGIN)
        eq1_5 = MathTex(r"x + g'(y) = x").move_to(ORIGIN)
        eq1_6 = MathTex(r"g'(y) = 0 \quad \Rightarrow \quad g(y) = C").move_to(ORIGIN)
        eq1_7 = MathTex(r"F(x, y) = \frac{x^2}{2} + xy + C").move_to(ORIGIN)
        eq1_8 = MathTex(r"\text{Since } dF = (x + y) \, dx + x \, dy, \text{ the differential is exact.}").move_to(ORIGIN)

        self.play(Write(description1))
        self.play(Write(eq1_1))
        self.wait(2)
        self.play(ReplacementTransform(eq1_1, eq1_2))
        self.wait(2)
        self.play(ReplacementTransform(eq1_2, eq1_3))
        self.wait(2)
        self.play(ReplacementTransform(eq1_3, eq1_4))
        self.wait(2)
        self.play(ReplacementTransform(eq1_4, eq1_5))
        self.wait(2)
        self.play(ReplacementTransform(eq1_5, eq1_6))
        self.wait(2)
        self.play(ReplacementTransform(eq1_6, eq1_7))
        self.wait(2)
        self.play(ReplacementTransform(eq1_7, eq1_8))
        self.wait(2)
        self.play(FadeOut(description1, eq1_8))

        # Section 2: Solve the differential equation (dy/dx + x + y = 0)
        description2 = MathTex(r"\text{Solve the differential equation } \frac{dy}{dx} + x + y = 0").to_edge(UP)
        eq2_1 = MathTex(r"\frac{dy}{dx} = -(x + y)").move_to(ORIGIN)
        eq2_2 = MathTex(r"\text{Integrating factor } \mu(x) = e^{\int 1 \, dx} = e^x").move_to(ORIGIN)
        eq2_3 = MathTex(r"e^x \frac{dy}{dx} + e^x(x + y) = 0").move_to(ORIGIN)
        eq2_4 = MathTex(r"\frac{d}{dx}(e^x y) = -xe^x").move_to(ORIGIN)
        eq2_5 = MathTex(r"e^x y = \int -xe^x \, dx").move_to(ORIGIN)
        eq2_6 = MathTex(r"\int -xe^x \, dx = -xe^x + \int e^x \, dx = -xe^x + e^x + C").move_to(ORIGIN)
        eq2_7 = MathTex(r"e^x y = -xe^x + e^x + C").move_to(ORIGIN)
        eq2_8 = MathTex(r"y = -x + 1 + Ce^{-x}").move_to(ORIGIN)
        eq2_9 = MathTex(r"\text{The general solution is } y = -x + 1 + Ce^{-x}").move_to(ORIGIN)

        self.play(Write(description2))
        self.play(Write(eq2_1))
        self.wait(2)
        self.play(ReplacementTransform(eq2_1, eq2_2))
        self.wait(2)
        self.play(ReplacementTransform(eq2_2, eq2_3))
        self.wait(2)
        self.play(ReplacementTransform(eq2_3, eq2_4))
        self.wait(2)
        self.play(ReplacementTransform(eq2_4, eq2_5))
        self.wait(2)
        self.play(ReplacementTransform(eq2_5, eq2_6))
        self.wait(2)
        self.play(ReplacementTransform(eq2_6, eq2_7))
        self.wait(2)
        self.play(ReplacementTransform(eq2_7, eq2_8))
        self.wait(2)
        self.play(ReplacementTransform(eq2_8, eq2_9))
        self.wait(2)
        self.play(FadeOut(description2, eq2_9))
