
from manim import *

class Solution(Scene):
    def construct(self):
        # Step description
        step_desc = MathTex(r"\text{Identify as linear first-order differential equation}").to_edge(UP).scale(0.75)
        
        # Equations
        eq1 = MathTex(r"\frac{dy}{dx} + P(x)y = Q(x)").move_to(ORIGIN).scale(0.75)
        eq2 = MathTex(r"P(x) = (2 - 3x^2)x^{-3}, \, Q(x) = 1").move_to(ORIGIN).scale(0.75)
        eq3 = MathTex(r"\mu(x) = e^{\int P(x) \, dx}").move_to(ORIGIN).scale(0.75)
        eq4 = MathTex(r"P(x) = \frac{2}{x^3} - 3x^{-1}").move_to(ORIGIN).scale(0.75)
        eq5 = MathTex(r"\int P(x) \, dx = \int \left( \frac{2}{x^3} - 3x^{-1} \right) \, dx").move_to(ORIGIN).scale(0.75)
        eq6 = MathTex(r"= \int 2x^{-3} \, dx - \int 3x^{-1} \, dx").move_to(ORIGIN).scale(0.75)
        eq7 = MathTex(r"= 2 \left( \frac{x^{-2}}{-2} \right) - 3 \ln |x|").move_to(ORIGIN).scale(0.75)
        eq8 = MathTex(r"= -x^{-2} - 3 \ln |x|").move_to(ORIGIN).scale(0.75)
        eq9 = MathTex(r"\mu(x) = e^{-x^{-2} - 3 \ln |x|}").move_to(ORIGIN).scale(0.75)
        eq10 = MathTex(r"\mu(x) = e^{-x^{-2}} \cdot e^{-3 \ln |x|}").move_to(ORIGIN).scale(0.75)
        eq11 = MathTex(r"= e^{-x^{-2}} \cdot |x|^{-3}").move_to(ORIGIN).scale(0.75)
        eq12 = MathTex(r"= \frac{e^{-x^{-2}}}{x^3}").move_to(ORIGIN).scale(0.75)
        eq13 = MathTex(r"\frac{e^{-x^{-2}}}{x^3} \frac{dy}{dx} + \frac{e^{-x^{-2}}}{x^3} \left( \frac{2}{x^3} - 3x^{-1} \right) y = \frac{e^{-x^{-2}}}{x^3}").move_to(ORIGIN).scale(0.75)
        eq14 = MathTex(r"\frac{d}{dx} \left( \frac{e^{-x^{-2}}}{x^3} y \right) = \frac{e^{-x^{-2}}}{x^3}").move_to(ORIGIN).scale(0.75)
        eq15 = MathTex(r"\int \frac{d}{dx} \left( \frac{e^{-x^{-2}}}{x^3} y \right) \, dx = \int \frac{e^{-x^{-2}}}{x^3} \, dx").move_to(ORIGIN).scale(0.75)
        eq16 = MathTex(r"\frac{e^{-x^{-2}}}{x^3} y = \int \frac{e^{-x^{-2}}}{x^3} \, dx + C").move_to(ORIGIN).scale(0.75)
        eq17 = MathTex(r"\int \frac{e^{-x^{-2}}}{x^3} \, dx = \frac{1}{2} \int e^u \, du").move_to(ORIGIN).scale(0.75)
        eq18 = MathTex(r"= \frac{1}{2} e^u + C").move_to(ORIGIN).scale(0.75)
        eq19 = MathTex(r"= \frac{1}{2} e^{-x^{-2}} + C").move_to(ORIGIN).scale(0.75)
        eq20 = MathTex(r"\frac{e^{-x^{-2}}}{x^3} y = \frac{1}{2} e^{-x^{-2}} + C").move_to(ORIGIN).scale(0.75)
        eq21 = MathTex(r"y = \frac{1}{2} x^3 + C x^3 e^{x^{-2}}").move_to(ORIGIN).scale(0.75)

        # Animations
        self.play(Write(step_desc))
        self.play(Write(eq1))
        self.wait(2)
        self.play(ReplacementTransform(eq1, eq2))
        self.wait(2)
        self.play(ReplacementTransform(eq2, eq3))
        self.wait(2)
        self.play(ReplacementTransform(eq3, eq4))
        self.wait(2)
        self.play(ReplacementTransform(eq4, eq5))
        self.wait(2)
        self.play(ReplacementTransform(eq5, eq6))
        self.wait(2)
        self.play(ReplacementTransform(eq6, eq7))
        self.wait(2)
        self.play(ReplacementTransform(eq7, eq8))
        self.wait(2)
        self.play(ReplacementTransform(eq8, eq9))
        self.wait(2)
        self.play(ReplacementTransform(eq9, eq10))
        self.wait(2)
        self.play(ReplacementTransform(eq10, eq11))
        self.wait(2)
        self.play(ReplacementTransform(eq11, eq12))
        self.wait(2)
        self.play(ReplacementTransform(eq12, eq13))
        self.wait(2)
        self.play(ReplacementTransform(eq13, eq14))
        self.wait(2)
        self.play(ReplacementTransform(eq14, eq15))
        self.wait(2)
        self.play(ReplacementTransform(eq15, eq16))
        self.wait(2)
        self.play(ReplacementTransform(eq16, eq17))
        self.wait(2)
        self.play(ReplacementTransform(eq17, eq18))
        self.wait(2)
        self.play(ReplacementTransform(eq18, eq19))
        self.wait(2)
        self.play(ReplacementTransform(eq19, eq20))
        self.wait(2)
        self.play(ReplacementTransform(eq20, eq21))
        self.wait(2)
        self.play(FadeOut(step_desc), FadeOut(eq21))
