
from manim import *

class Solution(Scene):
    def construct(self):
        # Section 1: Finding mu(x)
        description1 = MathTex(r"\text{Find } \mu(x) \text{ such that } df = 2\mu(x) \sin y \, dx - \mu(x)x \cos y \, dy \text{ is exact}").to_edge(UP).scale(0.75)
        eq1_1 = MathTex(r"\frac{\partial}{\partial y}(2\mu(x) \sin y) = \frac{\partial}{\partial x}(-\mu(x)x \cos y)").move_to(ORIGIN).scale(0.75)
        eq1_2 = MathTex(r"\frac{\partial}{\partial y}(2\mu(x) \sin y) = 2\mu(x) \cos y").move_to(ORIGIN).scale(0.75)
        eq1_3 = MathTex(r"\frac{\partial}{\partial x}(-\mu(x)x \cos y) = -\mu'(x)x \cos y - \mu(x) \cos y").move_to(ORIGIN).scale(0.75)
        eq1_4 = MathTex(r"2\mu(x) \cos y = -\mu'(x)x \cos y - \mu(x) \cos y").move_to(ORIGIN).scale(0.75)
        eq1_5 = MathTex(r"2\mu(x) = -\mu'(x)x - \mu(x)").move_to(ORIGIN).scale(0.75)
        eq1_6 = MathTex(r"3\mu(x) = -\mu'(x)x").move_to(ORIGIN).scale(0.75)
        eq1_7 = MathTex(r"\mu'(x)x = -3\mu(x)").move_to(ORIGIN).scale(0.75)
        eq1_8 = MathTex(r"\frac{\mu'(x)}{\mu(x)} = -\frac{3}{x}").move_to(ORIGIN).scale(0.75)
        eq1_9 = MathTex(r"\int \frac{\mu'(x)}{\mu(x)} \, dx = \int -\frac{3}{x} \, dx").move_to(ORIGIN).scale(0.75)
        eq1_10 = MathTex(r"\ln |\mu(x)| = -3 \ln |x| + C").move_to(ORIGIN).scale(0.75)
        eq1_11 = MathTex(r"|\mu(x)| = e^C \cdot |x|^{-3}").move_to(ORIGIN).scale(0.75)
        eq1_12 = MathTex(r"\mu(x) = C_1 x^{-3}").move_to(ORIGIN).scale(0.75)
        eq1_13 = MathTex(r"\mu(1) = 1 \implies C_1 = 1").move_to(ORIGIN).scale(0.75)
        eq1_14 = MathTex(r"\mu(x) = x^{-3}").move_to(ORIGIN).scale(0.75)

        self.play(Write(description1))
        self.play(Write(eq1_1))
        self.wait(2)
        self.play(ReplacementTransform(eq1_1, eq1_2))
        self.wait(2)
        self.play(ReplacementTransform(eq1_2, eq1_3))
        self.wait(2)
        self.play(ReplacementTransform(eq1_3, eq1_4))
        self.wait(2)
        self.play(ReplacementTransform(eq1_4, eq1_5))
        self.wait(2)
        self.play(ReplacementTransform(eq1_5, eq1_6))
        self.wait(2)
        self.play(ReplacementTransform(eq1_6, eq1_7))
        self.wait(2)
        self.play(ReplacementTransform(eq1_7, eq1_8))
        self.wait(2)
        self.play(ReplacementTransform(eq1_8, eq1_9))
        self.wait(2)
        self.play(ReplacementTransform(eq1_9, eq1_10))
        self.wait(2)
        self.play(ReplacementTransform(eq1_10, eq1_11))
        self.wait(2)
        self.play(ReplacementTransform(eq1_11, eq1_12))
        self.wait(2)
        self.play(ReplacementTransform(eq1_12, eq1_13))
        self.wait(2)
        self.play(ReplacementTransform(eq1_13, eq1_14))
        self.wait(2)
        self.play(FadeOut(description1, eq1_14))

        # Section 2: Finding f(x, y)
        description2 = MathTex(r"\text{Find } f(x, y) \text{ such that } df = 2x^{-3} \sin y \, dx - x^{-3}x \cos y \, dy").to_edge(UP).scale(0.75)
        eq2_1 = MathTex(r"f(x, y) = \int 2x^{-3} \sin y \, dx").move_to(ORIGIN).scale(0.75)
        eq2_2 = MathTex(r"f(x, y) = -x^{-2} \sin y + g(y)").move_to(ORIGIN).scale(0.75)
        eq2_3 = MathTex(r"\frac{\partial}{\partial y}(-x^{-2} \sin y + g(y)) = -x^{-2} \cos y").move_to(ORIGIN).scale(0.75)
        eq2_4 = MathTex(r"-x^{-2} \cos y + g'(y) = -x^{-2} \cos y").move_to(ORIGIN).scale(0.75)
        eq2_5 = MathTex(r"g'(y) = 0 \implies g(y) = C").move_to(ORIGIN).scale(0.75)
        eq2_6 = MathTex(r"f(x, y) = -x^{-2} \sin y + C").move_to(ORIGIN).scale(0.75)

        self.play(Write(description2))
        self.play(Write(eq2_1))
        self.wait(2)
        self.play(ReplacementTransform(eq2_1, eq2_2))
        self.wait(2)
        self.play(ReplacementTransform(eq2_2, eq2_3))
        self.wait(2)
        self.play(ReplacementTransform(eq2_3, eq2_4))
        self.wait(2)
        self.play(ReplacementTransform(eq2_4, eq2_5))
        self.wait(2)
        self.play(ReplacementTransform(eq2_5, eq2_6))
        self.wait(2)
        self.play(FadeOut(description2, eq2_6))
